### ISSUE TITLE
NPM version out of date?

### ISSUE THREAD

**Issue by baradhili** [maxal-studio/vuejs3-google-maps#1]
Noticed that yarn add vue3-google-maps seems to want vue 2.x ? Should I be adding dev-master instead?

**Comment by dajanvulaj** [comment]
Hello, the package name is not correct: `yarn add vuejs3-google-maps`

**Comment by baradhili** [comment]
You need to update your readme then :)

**Comment by dajanvulaj** [comment]
Yes sorry, thanks for letting me know! I'll update it now.
