### ISSUE TITLE
Stays stuck in map is loading

### ISSUE THREAD

**Issue by sandoche** [maxal-studio/vuejs3-google-maps#2]
Hi,

I am trying to use the library on my project but it stays stuck in "map is loading" and there is no error in the console nor in the query to google with the API.

**Comment by dajanvulaj** [comment]
Hello, sandoche.

Try changing **_ready_** to true and the map should autoload.
 

```js
 <PlaceSearch
    v-bind:ready="ready"
/>
```

Let me know if it works!
