### ISSUE TITLE
How to reload the saved location to update?

### ISSUE THREAD

**Issue by abidmaqbool20** [maxal-studio/vuejs3-google-maps#5]
I've saved different locations into the database and now I want my users to edit any of the saved locations. How can I reload a location into this widget?

Thanks in advance.

**Comment by dajanvulaj** [comment]
To reload data set :
```js
{
    fallbackProcedure: "manually", 
    manually: {
        address_description: "21 Dhjetori, Tirana, Albania",
        city: "Tirana",
        country: "Albania",
        lat: 41.3267905,
        lng: 19.8060475,
        state: "Tirana County",
        zip_code: "",
        zoom: 17,
    },
}
```

**Comment by abidmaqbool20** [comment]
I've tried this thing already. It doesn't load the autocomplete text box in the map widget. Also, the location marker get disappeared
